### ISSUE TITLE
Gromacs demo: move user_id and working_directory to the configuration file

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#14]

**Comment by andre-merzky** [comment]
This has been done in the fix/resource_configuration branch.  Please check it out, and let me know if you want that merged into devel.

**Comment by mturilli** [comment]
I must be missing something. I am in fix/resource_configuration but I see no changes to gromacs_demo.py. It still uses:

```
c1.user_id = 'merzky'
task_descr.executable        = '/N/u/marksant/bin/mdrun' (?!)
task_descr.working_directory = "/N/u/merzky/troy_demo/tasks/%d/" % n
```

Happy to test it once gromacs_demo.py will be updated and/or I will have understood what I am missing.

**Comment by marksantcroos** [comment]
Hi Matteo, I believe this is addressed in the latest incarnation.

**Comment by andre-merzky** [comment]
As discussed yesterday, that branch was merged into devel and deleted on github.
