### ISSUE TITLE
bigjob_pilot provisioner uses local user id for remote path

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.owms#16]
Should be a configurable?

**Comment by marksantcroos** [comment]
Also for sinon provisioner.

**Comment by andre-merzky** [comment]
Mark, can I close this tickets, i.e. is the fix/resource_configuration branch addressing this?

**Comment by marksantcroos** [comment]
For bigjob at least I had confirmed that it works.
Assuming similar changes were made for sinon than it can be closed!

Thanks!

**Comment by andre-merzky** [comment]
Yes, changed also apply for Sinon.
