### ISSUE TITLE
plugin_strategy_basic_late_binding.py aborts with partition fail

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#17]
Called from experiments_matteo.sh with saga-pilot:

2014:01:23 15:12:01 MainThread   troy.logger           : [ERROR   ] partition failed - abort
Traceback (most recent call last):
  File "bin/owms.py", line 645, in <module>
    main(args)
  File "bin/owms.py", line 184, in main
    workload_manager, strategy=args.troy_strategy)
  File "/N/u/mturilli/AIMES/ve/lib/python2.7/site-packages/troy/strategy.py", line 34, in execute_workload
    strategy.execute (workload_id, planner, overlay_mgr, workload_mgr)
  File "/N/u/mturilli/AIMES/ve/lib/python2.7/site-packages/pilot/filemanagement/../../troy/plugins/strategy/plugin_strategy_basic_late_binding.py", line 125, in execute
    raise RuntimeError ("partition failed - abort")
RuntimeError: partition failed - abort

**Comment by andre-merzky** [comment]
Thanks for mailing the log! In the log, I don't see data staging -- so I guess that it is still disabled, right?  In `//N/u/mturilli/agent` I see a `STDOUT` with `/bin/sh: hobot_0-task_2.sh: No such file or directory` -- which seems to make sense given that this shell script is indeed not there.  So, if the task working dir was set to `/N/u/mturilli/agent`, then that is probably the cause of the error.  How was the script supposed to get there w/o staging?

**Comment by mturilli** [comment]
Thank you, that addressed the issue. Maybe we should refine the error reporting...

**Comment by andre-merzky** [comment]
Yes, indeed -- that needs to be improved for both pilot failures and unit failures.  I'll open a separate ticket for that.
