### ISSUE TITLE
Log partition Vs workload

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#22]
Workload partitions are logged as follow:

```
bind_workload       :   0.09 sec
stage_in_workload   :  13.31 sec
dispatch_workload   :  31.79 sec
stage_out_workload  :  35.08 sec
```

It should probably be:

```
bind_workload_partition_<partition_id>       :   0.09 sec
stage_in_workload_partition_<partition_id>   :  13.31 sec
dispatch_workload_partition_<partition_id>   :  31.79 sec
stage_out_workload_partition_<partition_id>  :  35.08 sec
```

**Comment by andre-merzky** [comment]
You already added the method signature to the timer -- does that solve this ticket?

**Comment by mturilli** [comment]
Hi Andre,

I am not sure how your comment relates to the ticket. The problem reported is of naming in the logs. We should not call 'workload' a 'partition'. For example, I should not say that a workload has been bound - i.e. bind_workload : x.xx sec - when indeed is a workload partition to have been bound - i.e. bind_workload_partition_wlp.xxx : x.xx sec. When I was trying to write a parser for these logs, this imprecision in naming created a lot of problems. I will be happy to dwell into the code and fix it myself.

**Comment by andre-merzky** [comment]
Ah, I see... -- well, 'bind_workload' is the name of the method used, and there is no separation on _how_ the method is called, for binding a partition workload or a full workload.

In general, I don't think that parsing logfiles for timing information is a very scalable approach -- log files are really for debugging etc.  IMHO, timers should be part of the Troy inspection, eventually, and should not need manual parsing of arbitrary log strings at all... :/

If you don't mind, I close that ticket, as this item should be covered by (the now infamous) #24 already...

**Comment by mturilli** [comment]
I see your point about using logs but I take this naming issue as a
possible indication of confusion in the design/implementation of workload
and partitions. Anyway, I will start to look into the code and let you know
what I find.

On Mon, Jan 27, 2014 at 9:44 AM, Andre Merzky notifications@github.comwrote:

> Ah, I see... -- well, 'bind_workload' is the name of the method used, and
> there is no separation on _how_ the method is called, for binding a
> partition workload or a full workload.
> 
> In general, I don't think that parsing logfiles for timing information is
> a very scalable approach -- log files are really for debugging etc. IMHO,
> timers should be part of the Troy inspection, eventually, and should not
> need manual parsing of arbitrary log strings at all... :/
> 
> If you don't mind, I close that ticket, as this item should be covered by
> (the now infamous) #24 https://github.com/saga-project/troy/issues/24already...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saga-project/troy/issues/22#issuecomment-33372917
> .

## 

Dr Matteo Turilli
Department of Electrical and Computer Engineering
Rutgers University
