### ISSUE TITLE
Critical: saga-pilot plugin schedules pilots as multiple, 8-cores jobs

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#25]
Instead of submitting 1 job with n cores, the saga-pilot plugin submits n/8 jobs. For example:
- 32 tasks, 1 core each = 4 jobs, 8 cores each.
- 64 tasks, 1 core each = 8 jobs, 8 cores each.
- 128 tasks, 1 core each = 16 jobs, 8 cores each.
- ...

I have checked by submitting a 128 cores pilot via saga-pilot and I got a single job of 128 cores scheduled on FutureGrid.

This is a critical bug to address as it taints every experiment made with TROY.

**Comment by andre-merzky** [comment]
Can you please check how the default overlay translator plugin is configured for you?  I am using:

```
[overlay_translator_max_pilot_size]
pilot_size        = 4
```

The default is indeed '8' ...

**Comment by andre-merzky** [comment]
Added log info message to report used pilot size.

**Comment by mturilli** [comment]
Hi Andre,

I am not sure I understand the fix. The problem, as I see it, is that if we
give TROY a 128 task workload, I would expect a 128 cores pilot to be
created as a _single_ job on the remote resource or, at least, I would
expect this to be the default behavior.

On Mon, Jan 27, 2014 at 5:18 AM, Andre Merzky notifications@github.comwrote:

> Added log info message to report used pilot size.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saga-project/troy/issues/25#issuecomment-33355480
> .

## 

Dr Matteo Turilli
Department of Electrical and Computer Engineering
Rutgers University

**Comment by mturilli** [comment]
Reopened on the base of the discussion about ticket #20

**Comment by andre-merzky** [comment]
Well, the problem simply is that we have no sensible overlay translator plugin -- the only translator plugin is `pilot_max_size`.  Of course I can set the default max size to the size of the overlay, that would address this specific use case.  but in general, Troy needs intelligent plugins to make those kind of decisions...

**Comment by andre-merzky** [comment]
This is now implemented -- default should be unlimited.  I didn't test, Matteo -- could you please do that and close the ticket if that addresses your problem?   Thanks!

**Comment by mturilli** [comment]
Agreed on the intelligence but let start from the simple case as a base
line. I will run the tests and report back.

On Mon, Jan 27, 2014 at 8:47 AM, Andre Merzky notifications@github.comwrote:

> This is now implemented -- default should be unlimited. I didn't test,
> Matteo -- could you please do that and close the ticket if that addresses
> your problem? Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saga-project/troy/issues/25#issuecomment-33368378
> .

## 

Dr Matteo Turilli
Department of Electrical and Computer Engineering
Rutgers University

**Comment by andre-merzky** [comment]
This has confirmed working by latest the troy demo.
