### ISSUE TITLE
task output needs to be able to output to a specific directory otherwise all elements in the bag write to the same file

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.owms#27]
We probably need some file_transfer directives on the task output (and eventually also the input).

**Comment by andre-merzky** [comment]
This should be implemented now via 2c7743f.  I only tested with bigjob though, as I have trouble  with the agents on FG.  Can you please also test and close the ticket if things work ok?  FWIW, phase1_demo_3 uses file staging directives now.  The changes should be backward compatible (if no staging op is found, the string is interpreted as normal file path).

**Comment by marksantcroos** [comment]
thanks!
push?

**Comment by andre-merzky** [comment]
puuuuush!

**Comment by marksantcroos** [comment]
still dont see the commit though

**Comment by andre-merzky** [comment]
on branch 'fix/data_staging'?  

```
(ve)merzky@thinkie:~/saga/troy (fix/data_staging %) $ git push
Everything up-to-date

(ve)merzky@thinkie:~/saga/troy (fix/data_staging %) $ git describe --tags --always
0.0.1-457-g2c7743f
```

**Comment by marksantcroos** [comment]
probably only a local origin

**Comment by andre-merzky** [comment]
Ah, stupid me!!  Sorry for that...

A.

**Comment by marksantcroos** [comment]
Seems to work!
