### ISSUE TITLE
Clean, out-of-the-box installation from devel failing with 'No such plugin type strategy'

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#28]
Traceback (most recent call last):
  File "gromacs_demo.py", line 91, in <module>
    troy.execute_workload(workload_id, planner, overlay_mgr, workload_mgr, strategy='basic')
  File "/Users/mturilli/Virtualenvs/TROY/lib/python2.7/site-packages/troy/strategy.py", line 24, in execute_workload
    strategy   = plugin_mgr.load  ('strategy', strategy)
  File "/Users/mturilli/Virtualenvs/TROY/lib/python2.7/site-packages/radical/utils/plugin_manager.py", line 253, in load
    raise LookupError ("No such plugin type %s" % ptype)
LookupError: No such plugin type strategy

**Comment by andre-merzky** [comment]
Could that be a duplication of #12 / https://github.com/saga-project/radical.utils/issues/3 ?  Can you please send a DEBUG log?

Thanks, Andre.

**Comment by mturilli** [comment]
Yes, it is. Do we have an idea about when that bug in radical.utils will be fixed and then released?

**Comment by andre-merzky** [comment]
I'll triage this this week, depending on what causes it I can give you an estimate then.

**Comment by andre-merzky** [comment]
Matteo, Ashley -- could you please check if the bug is still present in troy devel / radical.utils devel?  It seems to work for me -- but I am not sure how much that means ;)

**Comment by andre-merzky** [comment]
Matteo, Ashley, waiting for report back.  I am going to close this for now, as it seems indeed gone - but please reopen if you still have that problem!  Please user radical.utils devel -- this fix will go into the next release...
