### ISSUE TITLE
plugin naming consistency

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.owms#39]
Troy uses short and long names for plugins, depending on context.  As config system will now switch to a hierarchical system, the long names can be phased out.

**Comment by mturilli** [comment]
Not for the end user config files please.

On Mon, Feb 3, 2014 at 11:48 AM, Andre Merzky notifications@github.comwrote:

> Troy uses short and long names for plugins, depending on context. As
> config system will now switch to a hierarchical system, the long names can
> be phased out.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/saga-project/troy/issues/39
> .

## 

Dr Matteo Turilli
Department of Electrical and Computer Engineering
Rutgers University

**Comment by andre-merzky** [comment]
Why not?  That is more pythonesqe, easier to structure, and the hierarchy reflects better what it is which is configured...

**Comment by mturilli** [comment]
Following a chat on IRC, happy to go for JSON for all the configuration
with _our_ home-made, super-duper parser.

On Mon, Feb 3, 2014 at 12:04 PM, Matteo Turilli matteo.turilli@gmail.comwrote:

> Not for the end user config files please.
> 
> On Mon, Feb 3, 2014 at 11:48 AM, Andre Merzky notifications@github.comwrote:
> 
> > Troy uses short and long names for plugins, depending on context. As
> > config system will now switch to a hierarchical system, the long names can
> > be phased out.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/saga-project/troy/issues/39
> > .
> 
> ## 
> 
> Dr Matteo Turilli
> Department of Electrical and Computer Engineering
> Rutgers University

## 

Dr Matteo Turilli
Department of Electrical and Computer Engineering
Rutgers University

**Comment by andre-merzky** [comment]
This has been addressed.
