### ISSUE TITLE
Isolate plugin loading problem on shared machine

### ISSUE THREAD

**Issue by ashleyz** [radical-cybertools/radical.owms#43]
TODO: Copy over local code which creates an issue loading proper plugins/passing attributes, then figure out if it's caused by changes on my end or symptom of plugin loader.

(apologies for brief ticket, in a hurry before the next meeting but do not want to forget)

**Comment by mturilli** [comment]
What do we do with this ticket?

**Comment by andre-merzky** [comment]
This is actually not needed anymore -- was a reminder for Ashley which became obsolete.  Thanks for looking through the tickets! :)
