### ISSUE TITLE
python setup.py build fails

### ISSUE THREAD

**Issue by ashleyz** [radical-cybertools/radical.owms#5]
```
(troy-env)ashley@longcat:~/troy$ python setup.py build
running build
running build_py
package init file 'troy/plugins/overlay_inspector/__init__.py' not found (or not a regular file)
package init file 'troy/plugins/overlay_translator/__init__.py' not found (or not a regular file)
package init file 'troy/plugins/overlay_provisioner/__init__.py' not found (or not a regular file)
package init file 'troy/plugins/workload_inspector/__init__.py' not found (or not a regular file)
```

**Comment by andre-merzky** [comment]
This is a warning that can safely be ignored.  I did not yet find out how to avoid that warning -- it is wrong (the adaptors don't need an `__init__.py`).

I'll leave the ticket open, should try again to fix this somehow.  Maybe I'll just give in and add the useless inits ... :P

**Comment by andre-merzky** [comment]
This has been `fixed` by adding useless `__init__.py` files.  That is how python rolls ;)
