### ISSUE TITLE
Timings: Getting/deriving the total run time for the whole session

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#53]
Currently, we have the start time of the session but not the end time in `session['events']`. Inferring the end time by polling the time of the 'Done' event from the last workload of the session is inaccurate and proving to be complex when having to average 'Done' times across n runs.

**Comment by andre-merzky** [comment]
Timing is recorded within the scope of a session, so the session has in fact not yet finished.  I can record the time of recording -- would that help?

**Comment by mturilli** [comment]
Hi Andre, yes, if that is easily feasible. Basically, I have no precise
requirements about how, I just need two values to subtract so to get the
duration of the whole session. I would also be happy with having the value
for the duration directly available from the timing module but it does not
cost too much to do it on my side. Shall these two (or single) value be
saved within the session chapter?

On Fri, Feb 28, 2014 at 6:47 PM, Andre Merzky notifications@github.comwrote:

> Timing is recorded within the scope of a session, so the session has in
> fact not yet finished. I can record the time of recording -- would that
> help?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/saga-project/troy/issues/53#issuecomment-36406619
> .

## 

Dr Matteo Turilli
Department of Electrical and Computer Engineering
Rutgers University

**Comment by andre-merzky** [comment]
This should be implemented now: just like 'timed_create', we now also log a 'timed_dump' event on the session.  Since you control the point of dumping in your code, that should hopefully give you a useful time stamp :) 

Best, Andre.
