### ISSUE TITLE
scrambled agent STDOUT

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.owms#55]
I frequently see at the end of the agent's STDOUT file:

```
################################################################################
## Launching sagapilot-agent for 8 cores.
## CMDLINE: python sagapilot-agent.py -d mongodb://localhost/ -n sagapilot -s 53079cbd71297f418310fa0c -p 53079cbe71297f418310fa0f -c 8 -t 1440 -l MPIRUN
^[[H^[[J
```

The last line clears the screen, which makes looking at the output from remote challenging...

**Comment by oleweidner** [comment]
I assume that this only happens on one specific machine (one of the FGs — forgot which one)? You have reported this in a different context. It comes from a screwed up PBS epilogue and can’t really be avoided :(

**Comment by andre-merzky** [comment]
Sierra.  And damned.

**Comment by andre-merzky** [comment]
Hmm, I don't see this happening on Sierra though.  How can I reproduce this?  I'd like to open a FG ticket then...
