### ISSUE TITLE
tutorial: get rid of local_appdir ideally

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.owms#57]
"pwd" would do.
(But dont want to work on that part now)

**Comment by andre-merzky** [comment]
but, as you said in the chat, pwd is the working directory -- which is usually the one were your shell is when calling the program, which may not really be what we mean with local_appdir...  I don't like the variable either, really, but am not sure what the better solution is...

**Comment by marksantcroos** [comment]
But we are talking about a tutorial here, right?
Where we can instruct the user to cd into the directory.

Which in all likelihood they would do anyway (I would at least, to check
the files!).
It might not be perfect, but it probably prevails over an hardcoded path in
the repo I think.

If you want to go beyond these two, we could get path from the location of
the module.
But that probably adds more complexity than it solves problems.

**Comment by andre-merzky** [comment]
Ah, ok - for the tutorial I agree.  Will do so.

**Comment by andre-merzky** [comment]
done
