### ISSUE TITLE
Version appears to be broken

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#58]
```
$ virtualenv ~/Virtualenvs/TROY_devel
$ . ~/Virtualenvs/TROY_devel/bin/activate
$ pip install --upgrade -e git://github.com/saga-project/troy.git@devel#egg=troy
$ troy-version
8c23997-feature/documentation
```

**Comment by mturilli** [comment]
$ git pull
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (3/3), done.
From github.com:saga-project/troy
   2375e95..ac8f0a2  devel      -> origin/devel
Merge made by the 'recursive' strategy.
 setup.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
$ pip install .
$ pip uninstall troy
$ pip install .
$ troy-version 
8c23997-feature/documentation

**Comment by andre-merzky** [comment]
fixed (phew)
