### ISSUE TITLE
Sample configuration files

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#61]
- What sample files do we have at the moment?
- What are their files names?
- Where are they located?
- Where should be place them within the module dir three?

**Comment by andre-merzky** [comment]
Samples are the tutorial configs, basically.  I still don't think they should be installed -- troy is now functional w/o any config file, by default.  Default location is now $HOME/.troy -- any config files in there will be used.

Matteo, did we converge on the installation?

**Comment by mturilli** [comment]
OK.

Matteo

On Thu, Feb 27, 2014 at 6:56 AM, Andre Merzky notifications@github.comwrote:

> Samples are the tutorial configs, basically. I still don't think they
> should be installed -- troy is now functional w/o any config file, by
> default. Default location is now $HOME/.troy -- any config files in there
> will be used.
> 
> Matteo, did we converge on the installation?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/saga-project/troy/issues/61#issuecomment-36234664
> .

## 

Dr Matteo Turilli
Department of Electrical and Computer Engineering
Rutgers University

**Comment by andre-merzky** [comment]
Matteo, did we converge on the installation?

**Comment by mturilli** [comment]
Apologies, I was too telegraphic. Yes, let's see how it goes with the users and decide whether we need to provide a set of default configuration files based on their feedback. Does it sound reasonable?

**Comment by andre-merzky** [comment]
Ok, agree.  I'll close this ticket then, for housekeeping, and we open another one if the need emerges, ok?

Thanks!
