### ISSUE TITLE
TODO list for the tutorial

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#62]
Please add/edit/update as you see fit:
- Write documentation for tutorial 1, 2, 3.
- Test tutorial 1, 2, 3 on Shantenu's machine.
- Create a tarball with tutorial subdirectory.

**Comment by mturilli** [comment]
- Start to write documentation for each plugin (not to be completed by the tutorial day)

**Comment by andre-merzky** [comment]
Going to close this, as those items are addressed (there is a separate ticket for the failing strategy)
