### ISSUE TITLE
other format for command line instructions

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.owms#66]
Because of the >, the snippets are not copy&pastable.

**Comment by andre-merzky** [comment]
Any suggestion?  Not using any indication on what is command line input and what is output will be confusing I guess.  Any indication though will require character-wise cut-and paste.  Hmmm....

**Comment by mturilli** [comment]
Hem, I am not sure I see the problem. I was able to C&P without any issue,
I simply did not select with my mouse the '>'... Anyway, in the sagapilot
tutorial there is no character prepended, users did not complain, so I
guess we do the same.

On Fri, Feb 28, 2014 at 6:45 PM, Andre Merzky notifications@github.comwrote:

> Any suggestion? Not using any indication on what is command line input and
> what is output will be confusing I guess. Any indication though will
> require character-wise cut-and paste. Hmmm....
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/saga-project/troy/issues/66#issuecomment-36406546
> .

## 

Dr Matteo Turilli
Department of Electrical and Computer Engineering
Rutgers University

**Comment by andre-merzky** [comment]
removed.
