### ISSUE TITLE
strategy execution failed: invalid dir (tutorial_01)

### ISSUE THREAD

**Issue by vshah505** [radical-cybertools/radical.owms#67]
2014:02:27 16:48:28 MainThread   troy.logger           : [INFO    ] staging_in input/topol.tpr < fork://localhost / /home/%(username)s//troy_tutorial/troy_tutorial_01_8/ / topol.tpr
2014:02:27 16:48:31 MainThread   troy.logger           : [CRITICAL] strategy execution failed: invalid dir 'file://localhost': /home/%(username)s/troy_tutorial/troy_tutorial_01_8 (/home/vshah505/troy_tutorial/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +398 (change_dir)  :  raise saga.BadParameter ("invalid dir '%s': %s" % (cwdurl, tgturl)))
2014:02:27 16:48:31 MainThread   troy.logger           : [WARNING ] shutting down workload: wl.0001
2014:02:27 16:48:31 MainThread   troy.logger           : [WARNING ] shutting down overlay: ol.0001
2014:02:27 16:48:31 MainThread   troy.logger           : [INFO    ] cancel pilot    p.0001

**Comment by marksantcroos** [comment]
What is your python version?
It seems the patterns are not expanded.

**Comment by vshah505** [comment]
The reason for the error was config_troy.json was not passed.

**Comment by andre-merzky** [comment]
Just a note: while it is true that passing the config_troy.json would have avoided this, the real error is exactly what is logged in the first two lines: troy tries file staging, but that strange path   (`/home/%(username)s/troy_tutorial/troy_tutorial_01_8`)  is not accepted.  If you look at the path, you'll see that the `username` placeholder is not expanded.  If you add a username to the resource config part in the application config, and if you also have an mdrun you can point to, then it should actually run on localhost...
