### ISSUE TITLE
messages from plugins at loadtime

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.owms#7]
Currently plugins report a "plugin created" message when they are "loaded", even if they are not used.
We might want to change this distinction / description to create more clarity.

**Comment by andre-merzky** [comment]
I already added proper logging to the PluginManager today - we now can remove the prints/logs from the plugins.

**Comment by marksantcroos** [comment]
Ah, interesting.
So whats the "cut-off"? Everything reporting that is related to the plugin structure can be left to the generic logging, and only plugin specific stuff should be reported?

**Comment by andre-merzky** [comment]
plugin loading and errors on loading should be reported by the plugin manager -- information on the plugin's execution and functionality by the plugin.  I am just making this up - does it make sense to you this way?

**Comment by marksantcroos** [comment]
Yes, thats what I meant I guess.
TODO: remove all logging from the plugins, but we can close this ticket.
