### ISSUE TITLE
pilot inspection test failed on branch devel

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.owms#8]
---

---

pilot

---

2013:12:02 22:21:38 MainThread   troy.logger           : [INFO    ] overlay  translate: define   pilot   1: p.0005
2013:12:02 22:21:38 MainThread   troy.logger           : [INFO    ] overlay  schedule : schedule pilot p.0003 to localhost
2013:12:02 22:21:38 MainThread   troy.logger           : [INFO    ] overlay  schedule : schedule pilot p.0004 to localhost
2013:12:02 22:21:38 MainThread   troy.logger           : [INFO    ] overlay  schedule : schedule pilot p.0005 to localhost
2013:12:02 22:21:40 MainThread   troy.logger           : [INFO    ] overlay  provision: provision pilot  {u'tag': u'pilot_1', 'size': u'2'} : ['bigjob:bj-bb2fb9c4-5b97-11e3-add1-c8e0eb16c649:localhost', bigjob:bj-bb2fb9c4-5b97-11e3-add1-c8e0eb16c649:localhost] 
2013:12:02 22:21:41 MainThread   troy.logger           : [INFO    ] overlay  provision: provision pilot  {u'tag': u'pilot_2', 'size': u'2'} : ['bigjob:bj-bc858fa6-5b97-11e3-add1-c8e0eb16c649:localhost', bigjob:bj-bc858fa6-5b97-11e3-add1-c8e0eb16c649:localhost] 
2013:12:02 22:21:43 MainThread   troy.logger           : [INFO    ] overlay  provision: provision pilot  {'size': 1} : ['bigjob:bj-bd32202c-5b97-11e3-add1-c8e0eb16c649:localhost', bigjob:bj-bd32202c-5b97-11e3-add1-c8e0eb16c649:localhost] 
2013:12:02 22:21:43 MainThread   troy.logger           : [INFO    ] workload translate: derive unit cu.0001            for t.0007
2013:12:02 22:21:43 MainThread   troy.logger           : [INFO    ] workload translate: derive unit cu.0002            for t.0008
2013:12:02 22:21:43 MainThread   troy.logger           : [INFO    ] workload schedule : assign unit cu.0001            to p.0003
2013:12:02 22:21:43 MainThread   troy.logger           : [INFO    ] workload schedule : assign unit cu.0002            to p.0004
2013:12:02 22:21:44 MainThread   troy.logger           : [INFO    ] workload dispatch : dispatch cu.0001            to ['bigjob:bj-bb2fb9c4-5b97-11e3-add1-c8e0eb16c649:localhost', bigjob:bj-bb2fb9c4-5b97-11e3-add1-c8e0eb16c649:localhost]
2013:12:02 22:21:46 MainThread   troy.logger           : [INFO    ] workload dispatch : dispatch cu.0002            to ['bigjob:bj-bc858fa6-5b97-11e3-add1-c8e0eb16c649:localhost', bigjob:bj-bc858fa6-5b97-11e3-add1-c8e0eb16c649:localhost]
# F
## FAIL: test pilot inspection

Traceback (most recent call last):
  File "/Users/mark/.virtualenv/troy/lib/python2.7/site-packages/nose-1.3.0-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/mark/proj/troy/troy/tests/unittests/pilot/test_inspection.py", line 113, in test_pilot_inspection
    assert (unit.state    == RUNNING),     "%s != RUNNING" % unit.state
AssertionError: Done != RUNNING

---

Ran 1 test in 24.435s

FAILED (failures=1)
RC: False

**Comment by andre-merzky** [comment]
Works now for Mark.
