### ISSUE TITLE
config initialisation in a more central place

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.owms#9]
Currently the config is initialized in the bundle manager, this should probably move a the main troy, **init**, but not sure whether that is the right place.

**Comment by andre-merzky** [comment]
This should go into the session - thanks, I'll take care of that, if thats
ok with you?

A.

On Mon, Dec 2, 2013 at 10:27 PM, Mark Santcroos notifications@github.comwrote:

> Currently the config is initialized in the bundle manager, this should
> probably move a the main troy, _init_, but not sure whether that is the
> right place.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saga-project/troy/issues/9
> .

## 

Nothing is really difficult.

**Comment by marksantcroos** [comment]
Sure, you are now the proud owner.

**Comment by andre-merzky** [comment]
And this is implemented.
